// Copyright 2026 Naadir Jeewa
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

package tools

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"k8s.io/utils/ptr"

	"github.com/randomvariable/mage-common/api/tools/v1alpha1"
)

// NpxInstaller installs tools by generating a shell shim that delegates
// to npx with a pinned package version.
type NpxInstaller struct{}

// Install creates a shim script at <platformToolsDir>/<tool.Name> that invokes
// npx with the pinned package and version. If the shim already exists and
// contains the correct version, installation is skipped.
func (n *NpxInstaller) Install(_ context.Context, tool v1alpha1.Tool, source *v1alpha1.ToolSource, toolsDir string) error {
	installed, err := n.IsInstalled(tool, toolsDir)
	if err != nil {
		return fmt.Errorf("checking existing npx shim for %q: %w", tool.Name, err)
	}

	if installed {
		return nil
	}

	dir := PlatformToolsDir(toolsDir)

	err = os.MkdirAll(dir, toolsDirPerm)
	if err != nil {
		return fmt.Errorf("creating tools directory %q: %w", dir, err)
	}

	shimPath := filepath.Join(dir, tool.Name)
	content := shimContent(ptr.Deref(source.Package, ""), ptr.Deref(tool.Version, ""))

	err = os.WriteFile(shimPath, []byte(content), shimPerm)
	if err != nil {
		return fmt.Errorf("writing npx shim for %q: %w", tool.Name, err)
	}

	return nil
}

// IsInstalled reports whether the shim script exists and contains the
// expected version string for the tool.
func (n *NpxInstaller) IsInstalled(tool v1alpha1.Tool, toolsDir string) (bool, error) {
	shimPath := filepath.Join(PlatformToolsDir(toolsDir), tool.Name)

	data, err := os.ReadFile(shimPath) //nolint:gosec // File path from trusted configuration
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}

		return false, fmt.Errorf("reading npx shim %q: %w", shimPath, err)
	}

	// Check that the shim contains the expected version marker.
	expected := versionMarker(ptr.Deref(tool.Version, ""))

	return strings.Contains(string(data), expected), nil
}

// RuntimeAvailable checks that npx is available on PATH.
func (n *NpxInstaller) RuntimeAvailable() error {
	_, err := exec.LookPath("npx")
	if err != nil {
		return fmt.Errorf("%w: npx: %w", ErrRuntimeNotFound, err)
	}

	return nil
}

// shimContent generates the shell shim script that delegates to npx.
func shimContent(pkg, version string) string {
	bare := BareVersion(version)

	return fmt.Sprintf(`#!/bin/sh
# Generated by mage-common — do not edit.
# version:%s
exec npx %s@%s "$@"
`, version, pkg, bare)
}

// versionMarker returns the string embedded in shims to identify the version.
func versionMarker(version string) string {
	return "# version:" + version
}
